### ISSUE TITLE
Add some sample icons to Sidebar Entry

### ISSUE THREAD

**Issue by fosco** [riourbana/react-sidebar-layout#1]
The `Sidebar.Entry` component expects an `icon` property which is currently not set.
It would be nice to add two suitable images and set them as icons for the sample menu entries (Welcome and About).

Just leave a comment if you want to tackle this one :)

**Comment by KBoohene** [comment]
I would like to work on it, would you mind if I use material UI icons on the sidebar?

**Comment by fosco** [comment]
Yes @KBoohene, it's all yours!
